const cookies = [
    { id: 1, 
    name: "ChocoChip", 
    price: 540.00, 
    img: "../cookies_images/cookie1.png" },
    { id: 2, 
    name: "Jam Thumbprint", 
    price: 250.00, 
    img: "../cookies_images/cookie8.png" },
    { id: 3, 
    name: "Macarons", 
    price: 350.00, 
    img: "../cookies_images/cookie3.png" },
    { id: 4, 
    name: "Caramel", 
    price: 375.00, 
    img: "../cookies_images/cookie4.png" },
    { id: 5, 
    name: "Oatmeal Raisin", 
    price: 350.00, 
    img: "../cookies_images/cookie5.png" },
    { id: 6, 
    name: "Gingerbread", 
    price: 330.00, 
    img: "../cookies_images/cookie6.png" },
    { id: 7, 
    name: "White ChocoChip", 
    price: 540.00, 
    img: "../cookies_images/cookie7.png" },
    { id: 8, 
    name: "Peanut Butter", 
    price: 375.00, 
    img: "../cookies_images/cookie2.png" }
];

export default cookies;