const testimonials = [
  {
    id: 1,
    name: "Lance Jarvis",
    location: "London, UK",
    avatar: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
    message: "The best coffee and pastries in town! The ambiance makes it a perfect spot to work or relax.",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Juliet Wright",
    location: "Sweden",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "Cup N Crave is my happy place. The staff is super friendly, and the cappuccino is a must-try.",
    rating: 4.6,
  },
  {
    id: 3,
    name: "Michael D.",
    location: "Austin, Texas",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D",
    message: "The variety of desserts is incredible. I always look forward to their seasonal specials!",
    rating: 4.9,
  },
  {
    id: 4,
    name: "Kylie Lutz",
    location: "Paris, France",
    avatar: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
    message: "From the decor to the delicious treats, everything is so well thought out. Highly recommend it!",
    rating: 5,
  },
  {
    id: 5,
    name: "Mark Twin",
    location: "Berlin, Germany",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "Excellent coffee, great service, and a lovely environment. Perfect for casual meetings.",
    rating: 4.7,
  },
  {
    id: 6,
    name: "Anne",
    location: "New York, USA",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D",
    message: "Their sandwiches are to die for! Always fresh and delicious. Can't recommend enough.",
    rating: 4.8,
  },
  {
    id: 7,
    name: "Emma Stone",
    location: "Los Angeles, USA",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "Cup N Crave is my go-to cafe for relaxing weekends. The iced mocha is a delight!",
    rating: 4.9,
  },
  {
    id: 8,
    name: "Daniel Craig",
    location: "Sydney, Australia",
    avatar: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
    message: "I love the cozy vibe and the wide selection of teas. The green tea latte is a must-try.",
    rating: 4.7,
  },
  {
    id: 9,
    name: "Sophia Lee",
    location: "Seoul, South Korea",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "Cup N Crave feels like home. Their freshly baked croissants are out of this world!",
    rating: 4.8,
  },
  {
    id: 10,
    name: "Liam Brown",
    location: "Toronto, Canada",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D",
    message: "The customer service is outstanding, and the coffee is consistently amazing.",
    rating: 4.9,
  },
  {
    id: 11,
    name: "Olivia Martin",
    location: "Mumbai, India",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "The masala chai is authentic and reminds me of home. The staff is incredibly warm.",
    rating: 5,
  },
  {
    id: 12,
    name: "Noah Evans",
    location: "Cape Town, South Africa",
    avatar: "https://a.storyblok.com/f/191576/1200x800/a3640fdc4c/profile_picture_maker_before.webp",
    message: "A hidden gem! Perfect for catching up with friends over a great cup of coffee.",
    rating: 4.8,
  },
  {
    id: 13,
    name: "Chloe Taylor",
    location: "Dubai, UAE",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "Their dessert menu is a game-changer. The chocolate lava cake is a dream come true!",
    rating: 4.9,
  },
  {
    id: 14,
    name: "Mason Hall",
    location: "Singapore",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?fm=jpg&q=60&w=3000&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8N3x8cHJvZmlsZXxlbnwwfHwwfHx8MA%3D%3D",
    message: "Cup N Crave always feels welcoming. Their seasonal drinks are always creative and tasty.",
    rating: 4.6,
  },
  {
    id: 15,
    name: "Ella Moore",
    location: "Tokyo, Japan",
    avatar: "https://cdn-icons-png.flaticon.com/512/3135/3135715.png",
    message: "I am in love with their matcha latte. The cafe vibe is perfect for a peaceful day.",
    rating: 5,
  }
];

export default testimonials;
